# Generated by Django 4.1.1 on 2022-12-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_alter_comment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=250),
        ),
    ]
